### PR TITLE
Bypass empty sheets & NAQT fix

### PR DESCRIPTION
**Pull request by dylanbowman314**
- One of the team name cells for NAQT had the wrong cell value.
- Added logic to pass empty sheets.

### CODE REVIEW

**Comment by denisfliu** [comment]
Hey Dylan, thanks for the fix! I never got around to testing the NAQT configuration but am planning to tonight. As a warning -- NAQT is pretty stringent on making sure we use their template, so just make sure the generated sqbs file matches their template. Please feel free to let me know of any more issues you notice!

**Comment by dylanbowman314** [comment]
Yep, will let you know of anything else. Thanks for setting up this project--I had no idea how we were going to do stats for SCT otherwise :)

**Comment by denisfliu** [comment]
> Yep, will let you know of anything else. Thanks for setting up this project--I had no idea how we were going to do stats for SCT otherwise :)

There are several major bugs in the code that I'll fix by tomorrow.

**Comment by dylanbowman314** [comment]
Do you need help with anything?

**Comment by denisfliu** [comment]
Nope, but I'll keep you posted. Could you add me on discord (uild) and we can talk if needed?

**Pull request merged**
